version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sigmasoftware
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0555:5432"

volumes:
  postgres_data:
